version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis

  web:
    build: ./web
    volumes:
      - ./terraform:/terraform
      - ./workers:/workers
    environment:
      - REDIS_URL=redis://redis:6379
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - "4567:4567"
    depends_on:
      - redis

  worker:
    build: ./web
    command: bundle exec sidekiq -r ./../workers/terraform_worker.rb
    volumes:
      - ./terraform:/terraform
      - ./workers:/workers
    environment:
      - REDIS_URL=redis://redis:6379
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    depends_on:
      - redis
